version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
  web:
    image: mydockerid2505/foodgram:final
    restart: always
    volumes:
      - ./static_volume:/code/static
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./foodgram/.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web