# Generated by Django 3.1.5 on 2021-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210122_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(help_text='в минутах', null=True, verbose_name='Время приготовления'),
        ),
    ]
