# Generated by Django 3.1.5 on 2021-01-24 19:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210122_1821'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('recipes', django.db.models.manager.Manager()),
            ],
        ),
    ]
