# Generated by Django 3.1.6 on 2021-02-06 09:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210205_1328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorite',
            managers=[
                ('favorite', django.db.models.manager.Manager()),
            ],
        ),
    ]
