# Generated by Django 3.1.5 on 2021-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210124_1954'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='purchase',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='checkbox_style',
            field=models.CharField(default=0, max_length=15, verbose_name='цвет тега'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=10, verbose_name='Название тега'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, max_length=20, verbose_name='Слаг тэга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(max_length=20, verbose_name='Единица измерения'),
        ),
    ]
