# Generated by Django 3.1.5 on 2021-01-27 19:12

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210127_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', validators=[recipes.validators.image_size_validator], verbose_name='Изображение'),
        ),
    ]
