# Generated by Django 3.1.5 on 2021-01-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210128_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='unit',
            new_name='units',
        ),
    ]
