name: Foodgram - CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies from requirements.txt
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
          pip install flake8
          run: flake8 .

      - name: Test with UnitTest
          run: python manage.py  test


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
